# @format

name: "[pg_mod] CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/pg_mod/**
  pull_request:
    paths:
      - packages/pg_mod/**

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test-pg-mod:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 54321:5432

    name: "[pg_mod] run tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Setup"
        uses: actions/setup-node@v3
        with:
          node-version-file: "packages/pg_mod/.nvmrc"
          cache: yarn
          cache-dependency-path: "packages/pg_mod/yarn.lock"
      - name: Install
        run: |
          cd packages/pg_mod/
          make install
      - name: Tests
        run: |
          cd packages/pg_mod/
          make tests
        env:
          DB_CONNECTION: postgresql://postgres:postgres@localhost:54321/postgres
